plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'application'
}

application {
    mainClass = 'com.yangzhiguo.scraper.MainKt'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0'
    implementation 'org.xerial:sqlite-jdbc:3.43.2.2'
    implementation 'org.slf4j:slf4j-simple:2.0.9'
}

tasks.named('run') {
    standardInput = System.in
}