-- mushroom.db alias_names 回填计划
-- 由 scripts/cluster_details.py 自动生成
-- 逻辑:同 Union-Find 簇内,所有非空 alias 成员合并去重,回填到空 alias 成员
-- 使用前请先 cp app/src/main/assets/mushroom.db app/src/main/assets/mushroom.db.bak

BEGIN TRANSACTION;

UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1537;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1539;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1542;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4103;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 524;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4625;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2070;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1563;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3612;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3117;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 562;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1075;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1076;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1082;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3130;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2116;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1093;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 76;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1100;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1108;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3163;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 610;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4194;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3688;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3689;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1136;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1648;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1651;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1140;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 122;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1149;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1150;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4224;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1156;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 135;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1679;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1168;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1169;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1173;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1174;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 664;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4769;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 170;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1194;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4267;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1201;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3249;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1719;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 186;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 698;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 702;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 192;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 193;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 194;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3784;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2249;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1232;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2259;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1236;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2260;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2777;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1244;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 734;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3296;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 226;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 744;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 745;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 746;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4331;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3308;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2285;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 750;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1265;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 758;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2806;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 251;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 252;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 263;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 776;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3848;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4361;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 267;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3340;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4362;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2830;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4878;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3345;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3347;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2849;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2854;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2856;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2865;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1858;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 325;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 837;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3910;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3913;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1874;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 857;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2906;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 862;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1889;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3430;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 359;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4454;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1386;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 876;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 3951;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4463;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1907;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 376;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1400;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1402;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 392;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1434;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 926;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4510;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4004;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2982;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1959;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 5032;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1450;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 429;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4013;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1455;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1456;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1466;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4542;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 459;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1486;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1487;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2003;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1492;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1502;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1503;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1007;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4085;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 4599;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 2553;
UPDATE mushroom_species SET alias_names = '["乳菇属一种"]' WHERE id = 1534;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3076;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 517;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1033;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4624;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4628;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 539;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4123;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 546;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1570;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 551;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1582;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3120;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2556;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2110;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1087;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2111;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2112;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2113;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3656;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4169;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4183;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2143;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 96;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3169;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2147;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4196;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1638;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4092;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4716;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3696;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 123;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 652;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1680;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 146;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2706;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3735;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 161;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2730;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1208;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 700;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3267;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2245;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4306;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4313;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 223;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2276;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3312;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3831;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1788;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3330;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3337;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2832;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2845;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3880;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 309;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2882;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3936;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4460;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3962;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3978;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2960;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1949;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1457;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4017;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 438;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3514;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2491;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 444;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1469;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 4539;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 449;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1484;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1490;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3545;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 3035;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 1523;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2037;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 2044;
UPDATE mushroom_species SET alias_names = '["蜡蘑"]' WHERE id = 511;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 516;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 4109;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3087;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3604;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3100;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2083;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3146;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3155;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2654;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2150;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 4719;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1148;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2189;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 142;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1204;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1206;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 699;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 704;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3781;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3788;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1234;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1246;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2796;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 4333;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2288;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2289;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2292;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1278;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2819;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2324;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2325;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3351;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2330;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3866;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1319;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1835;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1839;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2361;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 4427;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 849;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 866;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2930;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1395;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 4990;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2431;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1922;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1924;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3462;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 4489;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 910;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 404;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2965;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3491;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2984;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2991;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 432;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 433;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3505;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2995;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 2998;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 439;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3512;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 4027;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3008;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3013;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1990;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3014;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3020;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3053;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1008;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 1528;
UPDATE mushroom_species SET alias_names = '["黏盖乳牛肝菌", "乳牛肝菌"]' WHERE id = 3072;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 3980;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 270;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 5775;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 1041;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 1425;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 275;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 4626;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 3221;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 4246;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 3226;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 285;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 1950;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 1827;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 293;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 4264;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 5033;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 299;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 3380;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 323;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 1860;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 2759;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 202;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 2251;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 3148;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 205;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 3276;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 2133;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 217;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 2907;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 220;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 2656;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 2919;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 4200;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 3965;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 4079;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 4209;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 1653;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 3061;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 4469;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 1659;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 3709;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 382;
UPDATE mushroom_species SET alias_names = '["块鳞灰鹅膏", "灰鹅膏", "卷边桩菇", "卷缘网褶菌"]' WHERE id = 3200;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 2051;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 904;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 2699;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 917;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 5398;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 3237;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 552;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 3885;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 1838;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 2096;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 817;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 2226;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 2481;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 3065;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 1212;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 1468;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 1346;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 707;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 324;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 836;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 1477;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 328;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 1864;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 1355;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 3577;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 342;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 856;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 989;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 478;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 1375;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 2142;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 3300;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 3302;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 3304;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 491;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 495;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 2419;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 500;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 4472;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 1913;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 1407;
UPDATE mushroom_species SET alias_names = '["红鳞疣柄牛肝菌"]' WHERE id = 768;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 2948;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 2055;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 1800;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 2069;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 4757;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 155;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 1961;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 2477;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 2868;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 2742;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 3260;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 4029;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 1859;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 74;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 2250;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 3151;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 3834;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 1240;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 601;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 91;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 3164;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 3295;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 741;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 1896;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 105;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 617;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 618;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 1002;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 2536;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 3306;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 5490;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 2035;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 759;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 120;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 1527;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 1783;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 4347;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 124;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 4983;
UPDATE mushroom_species SET alias_names = '["鳞盖褶孔牛肝", "鳞盖褶孔牛肝菌"]' WHERE id = 2943;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 2305;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 3714;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 1290;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 3083;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 272;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 1810;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 3992;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 3112;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 553;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 1321;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 1964;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 2480;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 436;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 3126;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 3638;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 568;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 1465;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 4163;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 3268;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 332;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 2768;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 2261;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 88;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 729;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 3930;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 4186;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 3553;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 2788;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 2916;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 103;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 490;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 1901;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 1778;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 1011;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 247;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 2810;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 2814;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 2047;
UPDATE mushroom_species SET alias_names = '["丝盖伞", "丝盖伞一种"]' WHERE id = 2688;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3202;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4354;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4355;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4356;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4611;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4363;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 268;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3085;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 2959;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3225;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3111;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 2858;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 310;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3385;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3386;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4409;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 5824;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 68;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3269;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3780;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4174;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3929;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4826;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 2779;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4443;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4572;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4835;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4453;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4712;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4459;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4590;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4464;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4465;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 4594;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3444;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 5236;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3832;
UPDATE mushroom_species SET alias_names = '["日本红菇"]' WHERE id = 3193;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 2435;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 2440;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 531;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 532;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 4121;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 3869;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 673;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 2338;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 2085;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 1330;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 1846;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 1471;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 1473;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 1348;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 1476;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 4679;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 3017;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 4297;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 716;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 717;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 2125;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 2252;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 1878;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 471;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 855;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 3799;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 2015;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 3040;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 2280;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 4207;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 4851;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 3968;
UPDATE mushroom_species SET alias_names = '["褐盖鹅膏近似种", "赭盖鹅膏", "斜盖伞"]' WHERE id = 5498;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3089;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 5653;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 5654;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 2967;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 4639;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3617;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3108;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3753;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 4009;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 5036;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 5039;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3760;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3252;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3382;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 442;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3515;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 2108;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3646;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3398;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 78;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3418;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 3934;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 4195;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 1513;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 4592;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 241;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 2803;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 1404;
UPDATE mushroom_species SET alias_names = '["粉红铆钉菇", "红铆钉菇", "红蜡蘑"]' WHERE id = 4093;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 3843;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 5497;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 905;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 3353;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 1692;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 3741;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 1954;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 2853;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 1710;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 1726;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 2879;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 3275;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 1485;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 1499;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 1116;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 2912;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 1763;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 1126;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 5858;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 5859;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 2538;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 2666;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 2541;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 1519;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 2552;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 5495;
UPDATE mushroom_species SET alias_names = '["小豹斑鹅膏", "豹斑毒蝇伞", "暗红粉孢牛肝菌"]' WHERE id = 125;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 2050;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 260;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 3973;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 4233;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 3090;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 3223;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 2716;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 2219;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 3756;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 4908;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 4919;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 4920;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 5819;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 3778;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 72;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 4553;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 4446;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 2399;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 481;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 4329;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 3438;
UPDATE mushroom_species SET alias_names = '["厚集毛菌"]' WHERE id = 4473;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 386;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 902;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 2184;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 1681;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 157;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 1310;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 1572;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 4518;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 2615;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 4682;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 203;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 1104;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 4180;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 3033;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 5345;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 1378;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 1522;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 1016;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 1657;
UPDATE mushroom_species SET alias_names = '["星孢寄生菇", "星孢菌寄生伞", "小脆柄菇"]' WHERE id = 1021;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 915;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 4372;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 2971;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 2335;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 2852;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 2981;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 4660;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 2488;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 2105;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 1218;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 2767;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 4304;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 850;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 3928;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 4067;
UPDATE mushroom_species SET alias_names = '["松塔牛肝菌", "松塔菌", "网孢牛肝菌", "黑牛肝菌"]' WHERE id = 1397;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 130;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 1934;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 3214;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 2704;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 4753;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 5263;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 2709;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 2970;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 416;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 3754;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 1965;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 3776;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 585;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 1251;
UPDATE mushroom_species SET alias_names = '["黄鳞鹅膏"]' WHERE id = 3326;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 2918;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 3078;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 3560;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 3782;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 269;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 273;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 2705;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 631;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 472;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 377;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 3098;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 4440;
UPDATE mushroom_species SET alias_names = '["虎皮乳牛肝菌"]' WHERE id = 4064;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 4873;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 2346;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 3050;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 4939;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 365;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 4016;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 2161;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 5754;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 4787;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 2901;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 1306;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 3579;
UPDATE mushroom_species SET alias_names = '["破皮裂盖伞", "裂丝盖伞"]' WHERE id = 1980;
UPDATE mushroom_species SET alias_names = '["匙盖假花耳", "匙形假花耳"]' WHERE id = 2663;
UPDATE mushroom_species SET alias_names = '["匙盖假花耳", "匙形假花耳"]' WHERE id = 235;
UPDATE mushroom_species SET alias_names = '["匙盖假花耳", "匙形假花耳"]' WHERE id = 3309;
UPDATE mushroom_species SET alias_names = '["匙盖假花耳", "匙形假花耳"]' WHERE id = 2066;
UPDATE mushroom_species SET alias_names = '["匙盖假花耳", "匙形假花耳"]' WHERE id = 467;
UPDATE mushroom_species SET alias_names = '["匙盖假花耳", "匙形假花耳"]' WHERE id = 179;
UPDATE mushroom_species SET alias_names = '["匙盖假花耳", "匙形假花耳"]' WHERE id = 4115;
UPDATE mushroom_species SET alias_names = '["匙盖假花耳", "匙形假花耳"]' WHERE id = 1177;
UPDATE mushroom_species SET alias_names = '["匙盖假花耳", "匙形假花耳"]' WHERE id = 1530;
UPDATE mushroom_species SET alias_names = '["新苦粉孢牛肝菌"]' WHERE id = 4250;
UPDATE mushroom_species SET alias_names = '["新苦粉孢牛肝菌"]' WHERE id = 4452;
UPDATE mushroom_species SET alias_names = '["新苦粉孢牛肝菌"]' WHERE id = 1931;
UPDATE mushroom_species SET alias_names = '["新苦粉孢牛肝菌"]' WHERE id = 5099;
UPDATE mushroom_species SET alias_names = '["新苦粉孢牛肝菌"]' WHERE id = 3093;
UPDATE mushroom_species SET alias_names = '["新苦粉孢牛肝菌"]' WHERE id = 3094;
UPDATE mushroom_species SET alias_names = '["新苦粉孢牛肝菌"]' WHERE id = 3195;
UPDATE mushroom_species SET alias_names = '["新苦粉孢牛肝菌"]' WHERE id = 3995;
UPDATE mushroom_species SET alias_names = '["新苦粉孢牛肝菌"]' WHERE id = 4031;
UPDATE mushroom_species SET alias_names = '["红丝膜菌", "血红丝膜菌"]' WHERE id = 2212;
UPDATE mushroom_species SET alias_names = '["红丝膜菌", "血红丝膜菌"]' WHERE id = 69;
UPDATE mushroom_species SET alias_names = '["红丝膜菌", "血红丝膜菌"]' WHERE id = 1736;
UPDATE mushroom_species SET alias_names = '["红丝膜菌", "血红丝膜菌"]' WHERE id = 2750;
UPDATE mushroom_species SET alias_names = '["红丝膜菌", "血红丝膜菌"]' WHERE id = 2737;
UPDATE mushroom_species SET alias_names = '["红丝膜菌", "血红丝膜菌"]' WHERE id = 3070;
UPDATE mushroom_species SET alias_names = '["红丝膜菌", "血红丝膜菌"]' WHERE id = 3317;
UPDATE mushroom_species SET alias_names = '["红丝膜菌", "血红丝膜菌"]' WHERE id = 1216;
UPDATE mushroom_species SET alias_names = '["粉孢牛肝菌"]' WHERE id = 674;
UPDATE mushroom_species SET alias_names = '["粉孢牛肝菌"]' WHERE id = 4647;
UPDATE mushroom_species SET alias_names = '["粉孢牛肝菌"]' WHERE id = 2152;
UPDATE mushroom_species SET alias_names = '["粉孢牛肝菌"]' WHERE id = 586;
UPDATE mushroom_species SET alias_names = '["粉孢牛肝菌"]' WHERE id = 1515;
UPDATE mushroom_species SET alias_names = '["粉孢牛肝菌"]' WHERE id = 183;
UPDATE mushroom_species SET alias_names = '["粉孢牛肝菌"]' WHERE id = 604;
UPDATE mushroom_species SET alias_names = '["粉孢牛肝菌"]' WHERE id = 3904;
UPDATE mushroom_species SET alias_names = '["疣孢褐盘菌"]' WHERE id = 4420;
UPDATE mushroom_species SET alias_names = '["疣孢褐盘菌"]' WHERE id = 2728;
UPDATE mushroom_species SET alias_names = '["疣孢褐盘菌"]' WHERE id = 2827;
UPDATE mushroom_species SET alias_names = '["疣孢褐盘菌"]' WHERE id = 3179;
UPDATE mushroom_species SET alias_names = '["疣孢褐盘菌"]' WHERE id = 4239;
UPDATE mushroom_species SET alias_names = '["疣孢褐盘菌"]' WHERE id = 5103;
UPDATE mushroom_species SET alias_names = '["疣孢褐盘菌"]' WHERE id = 3165;
UPDATE mushroom_species SET alias_names = '["榛蘑", "蜜色环菌", "奥氏蜜环菌", "蜜环菌"]' WHERE id = 1565;
UPDATE mushroom_species SET alias_names = '["榛蘑", "蜜色环菌", "奥氏蜜环菌", "蜜环菌"]' WHERE id = 3247;
UPDATE mushroom_species SET alias_names = '["榛蘑", "蜜色环菌", "奥氏蜜环菌", "蜜环菌"]' WHERE id = 5182;
UPDATE mushroom_species SET alias_names = '["榛蘑", "蜜色环菌", "奥氏蜜环菌", "蜜环菌"]' WHERE id = 1607;
UPDATE mushroom_species SET alias_names = '["榛蘑", "蜜色环菌", "奥氏蜜环菌", "蜜环菌"]' WHERE id = 1608;
UPDATE mushroom_species SET alias_names = '["榛蘑", "蜜色环菌", "奥氏蜜环菌", "蜜环菌"]' WHERE id = 3705;
UPDATE mushroom_species SET alias_names = '["榛蘑", "蜜色环菌", "奥氏蜜环菌", "蜜环菌"]' WHERE id = 1022;
UPDATE mushroom_species SET alias_names = '["盔孢伞"]' WHERE id = 5860;
UPDATE mushroom_species SET alias_names = '["盔孢伞"]' WHERE id = 1994;
UPDATE mushroom_species SET alias_names = '["盔孢伞"]' WHERE id = 5579;
UPDATE mushroom_species SET alias_names = '["盔孢伞"]' WHERE id = 5871;
UPDATE mushroom_species SET alias_names = '["盔孢伞"]' WHERE id = 2583;
UPDATE mushroom_species SET alias_names = '["盔孢伞"]' WHERE id = 538;
UPDATE mushroom_species SET alias_names = '["盔孢伞"]' WHERE id = 1467;
UPDATE mushroom_species SET alias_names = '["东方耳匙菌"]' WHERE id = 4866;
UPDATE mushroom_species SET alias_names = '["东方耳匙菌"]' WHERE id = 4867;
UPDATE mushroom_species SET alias_names = '["东方耳匙菌"]' WHERE id = 3749;
UPDATE mushroom_species SET alias_names = '["东方耳匙菌"]' WHERE id = 4326;
UPDATE mushroom_species SET alias_names = '["东方耳匙菌"]' WHERE id = 3568;
UPDATE mushroom_species SET alias_names = '["东方耳匙菌"]' WHERE id = 4785;
UPDATE mushroom_species SET alias_names = '["东方耳匙菌"]' WHERE id = 4880;
UPDATE mushroom_species SET alias_names = '["金黄鳞盖伞"]' WHERE id = 99;
UPDATE mushroom_species SET alias_names = '["金黄鳞盖伞"]' WHERE id = 3204;
UPDATE mushroom_species SET alias_names = '["金黄鳞盖伞"]' WHERE id = 3178;
UPDATE mushroom_species SET alias_names = '["金黄鳞盖伞"]' WHERE id = 75;
UPDATE mushroom_species SET alias_names = '["金黄鳞盖伞"]' WHERE id = 4653;
UPDATE mushroom_species SET alias_names = '["金黄鳞盖伞"]' WHERE id = 245;
UPDATE mushroom_species SET alias_names = '["云南褶孔牛肝菌"]' WHERE id = 3588;
UPDATE mushroom_species SET alias_names = '["云南褶孔牛肝菌"]' WHERE id = 4105;
UPDATE mushroom_species SET alias_names = '["云南褶孔牛肝菌"]' WHERE id = 3622;
UPDATE mushroom_species SET alias_names = '["云南褶孔牛肝菌"]' WHERE id = 2758;
UPDATE mushroom_species SET alias_names = '["云南褶孔牛肝菌"]' WHERE id = 2762;
UPDATE mushroom_species SET alias_names = '["云南褶孔牛肝菌"]' WHERE id = 3196;
UPDATE mushroom_species SET alias_names = '["亚白环黏小奥德蘑"]' WHERE id = 1733;
UPDATE mushroom_species SET alias_names = '["亚白环黏小奥德蘑"]' WHERE id = 2859;
UPDATE mushroom_species SET alias_names = '["亚白环黏小奥德蘑"]' WHERE id = 2094;
UPDATE mushroom_species SET alias_names = '["亚白环黏小奥德蘑"]' WHERE id = 1199;
UPDATE mushroom_species SET alias_names = '["亚白环黏小奥德蘑"]' WHERE id = 5142;
UPDATE mushroom_species SET alias_names = '["亚白环黏小奥德蘑"]' WHERE id = 4281;
UPDATE mushroom_species SET alias_names = '["红鳞丝膜菌"]' WHERE id = 5244;
UPDATE mushroom_species SET alias_names = '["红鳞丝膜菌"]' WHERE id = 3253;
UPDATE mushroom_species SET alias_names = '["红鳞丝膜菌"]' WHERE id = 1756;
UPDATE mushroom_species SET alias_names = '["红鳞丝膜菌"]' WHERE id = 5820;
UPDATE mushroom_species SET alias_names = '["红鳞丝膜菌"]' WHERE id = 2975;
UPDATE mushroom_species SET alias_names = '["囊孔附毛菌", "斑柄小脆柄菇"]' WHERE id = 3236;
UPDATE mushroom_species SET alias_names = '["囊孔附毛菌", "斑柄小脆柄菇"]' WHERE id = 331;
UPDATE mushroom_species SET alias_names = '["囊孔附毛菌", "斑柄小脆柄菇"]' WHERE id = 4277;
UPDATE mushroom_species SET alias_names = '["囊孔附毛菌", "斑柄小脆柄菇"]' WHERE id = 2426;
UPDATE mushroom_species SET alias_names = '["囊孔附毛菌", "斑柄小脆柄菇"]' WHERE id = 954;
UPDATE mushroom_species SET alias_names = '["皂腻口蘑", "皂味口蘑", "皂口蘑"]' WHERE id = 11;
UPDATE mushroom_species SET alias_names = '["皂腻口蘑", "皂味口蘑", "皂口蘑"]' WHERE id = 4339;
UPDATE mushroom_species SET alias_names = '["皂腻口蘑", "皂味口蘑", "皂口蘑"]' WHERE id = 697;
UPDATE mushroom_species SET alias_names = '["皂腻口蘑", "皂味口蘑", "皂口蘑"]' WHERE id = 4351;
UPDATE mushroom_species SET alias_names = '["小托柄鹅膏", "粉状鹅膏"]' WHERE id = 362;
UPDATE mushroom_species SET alias_names = '["小托柄鹅膏", "粉状鹅膏"]' WHERE id = 3630;
UPDATE mushroom_species SET alias_names = '["小托柄鹅膏", "粉状鹅膏"]' WHERE id = 5809;
UPDATE mushroom_species SET alias_names = '["小托柄鹅膏", "粉状鹅膏"]' WHERE id = 5181;
UPDATE mushroom_species SET alias_names = '["褶孔牛肝菌"]' WHERE id = 5708;
UPDATE mushroom_species SET alias_names = '["褶孔牛肝菌"]' WHERE id = 5201;
UPDATE mushroom_species SET alias_names = '["褶孔牛肝菌"]' WHERE id = 5813;
UPDATE mushroom_species SET alias_names = '["褶孔牛肝菌"]' WHERE id = 3643;
UPDATE mushroom_species SET alias_names = '["长柄珊瑚菌"]' WHERE id = 65;
UPDATE mushroom_species SET alias_names = '["长柄珊瑚菌"]' WHERE id = 5161;
UPDATE mushroom_species SET alias_names = '["长柄珊瑚菌"]' WHERE id = 3870;
UPDATE mushroom_species SET alias_names = '["烟褐炭黑牛肝菌"]' WHERE id = 87;
UPDATE mushroom_species SET alias_names = '["烟褐炭黑牛肝菌"]' WHERE id = 93;
UPDATE mushroom_species SET alias_names = '["烟褐炭黑牛肝菌"]' WHERE id = 3614;
UPDATE mushroom_species SET alias_names = '["褐环粘盖牛肝菌", "粘柄牛肝菌", "Slippery Jack", "松蘑"]' WHERE id = 4378;
UPDATE mushroom_species SET alias_names = '["褐环粘盖牛肝菌", "粘柄牛肝菌", "Slippery Jack", "松蘑"]' WHERE id = 4247;
UPDATE mushroom_species SET alias_names = '["褐环粘盖牛肝菌", "粘柄牛肝菌", "Slippery Jack", "松蘑"]' WHERE id = 5110;
UPDATE mushroom_species SET alias_names = '["大金钱菌属一种"]' WHERE id = 2049;
UPDATE mushroom_species SET alias_names = '["大金钱菌属一种"]' WHERE id = 1723;
UPDATE mushroom_species SET alias_names = '["大金钱菌属一种"]' WHERE id = 349;
UPDATE mushroom_species SET alias_names = '["美味牛肝", "白牛肝菌"]' WHERE id = 2274;
UPDATE mushroom_species SET alias_names = '["美味牛肝", "白牛肝菌"]' WHERE id = 1123;
UPDATE mushroom_species SET alias_names = '["美味牛肝", "白牛肝菌"]' WHERE id = 4148;
UPDATE mushroom_species SET alias_names = '["胶陀盘菌"]' WHERE id = 3233;
UPDATE mushroom_species SET alias_names = '["胶陀盘菌"]' WHERE id = 795;
UPDATE mushroom_species SET alias_names = '["黑点牛肝菌"]' WHERE id = 4519;
UPDATE mushroom_species SET alias_names = '["黑点牛肝菌"]' WHERE id = 30;
UPDATE mushroom_species SET alias_names = '["润滑锤舌菌", "jelly baby", "green slime fungus"]' WHERE id = 3047;
UPDATE mushroom_species SET alias_names = '["润滑锤舌菌", "jelly baby", "green slime fungus"]' WHERE id = 1868;
UPDATE mushroom_species SET alias_names = '["淡红褶孔牛肝菌"]' WHERE id = 3183;
UPDATE mushroom_species SET alias_names = '["淡红褶孔牛肝菌"]' WHERE id = 3166;
UPDATE mushroom_species SET alias_names = '["十字孢粉褶蕈"]' WHERE id = 2874;
UPDATE mushroom_species SET alias_names = '["十字孢粉褶蕈"]' WHERE id = 5309;
UPDATE mushroom_species SET alias_names = '["鸡油菌状湿伞"]' WHERE id = 4294;
UPDATE mushroom_species SET alias_names = '["鸡油菌状湿伞"]' WHERE id = 5132;
UPDATE mushroom_species SET alias_names = '["黄环变红鹅膏"]' WHERE id = 4633;
UPDATE mushroom_species SET alias_names = '["黄环变红鹅膏"]' WHERE id = 3996;
UPDATE mushroom_species SET alias_names = '["荫生丝盖伞"]' WHERE id = 3188;
UPDATE mushroom_species SET alias_names = '["荫生丝盖伞"]' WHERE id = 5268;
UPDATE mushroom_species SET alias_names = '["玫黄牛肝菌"]' WHERE id = 43;
UPDATE mushroom_species SET alias_names = '["斑盖褶孔牛肝菌"]' WHERE id = 3645;
UPDATE mushroom_species SET alias_names = '["洁小菇"]' WHERE id = 322;
UPDATE mushroom_species SET alias_names = '["变色栓菌", "云芝", "彩绒革盖菌"]' WHERE id = 510;
UPDATE mushroom_species SET alias_names = '["魏氏集毛菌"]' WHERE id = 3580;
UPDATE mushroom_species SET alias_names = '["假垂边红孢牛肝菌"]' WHERE id = 583;
UPDATE mushroom_species SET alias_names = '["毛足乳菇"]' WHERE id = 1447;
UPDATE mushroom_species SET alias_names = '["烟管孔菌", "烟色烟管菌"]' WHERE id = 4276;
UPDATE mushroom_species SET alias_names = '["白棕口蘑", "白褐口蘑"]' WHERE id = 3297;
UPDATE mushroom_species SET alias_names = '["斜盖伞属一种"]' WHERE id = 4052;
UPDATE mushroom_species SET alias_names = '["小薄孔菌", "小薄孔菌属一种"]' WHERE id = 2303;
UPDATE mushroom_species SET alias_names = '["毛舌菌", "毛舌菌原变种"]' WHERE id = 3046;
UPDATE mushroom_species SET alias_names = '["库恩菇", "鳞皮蘑", "sheathed woodtuft"]' WHERE id = 2820;

COMMIT;
-- 共计划更新 827 条